name: LLM Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3 # Menggunakan versi terbaru
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Menggunakan versi terbaru
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2 # Menggunakan versi terbaru
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Pastikan secrets ditambahkan
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Pastikan secrets ditambahkan
      - 
        name: Build and push Docker Image
        run: |
          docker build -t mutiaracitra/llm-generator:latest . 
          docker push mutiaracitra/llm-generator:latest       
